### ISSUE TITLE
PHP cant open it

### ISSUE THREAD

**Issue by Jeroenyouknow** [abcdan/discord-hook#2]
I cant open this on PHP.
Pls fix 
UwU

**Comment by abcdan** [comment]
Heya @Jeroenyouknow!

The library is made for Node.js so of course, you can't run it with PHP.
If you want to, you can port this library to PHP if you like to. The code should be easily readable.

Let me know if you need anything else.

- abcdan

**Comment by Jeroenyouknow** [comment]
Hi @abcdan,
Tnx i will look into it.

**Comment by lukasvdberk** [comment]
When is a port for python coming?
